package com.hyf.facebook.demo.conversions.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;

/**
 *
 * @author winfun
 * @date 2021/2/1 3:24 下午
 **/
@Data
public class UserData {

    /**
     * The IP address of the browser corresponding to the event.
     * Do not hash
     */
    @JsonProperty("client_ip_address")
    private String clientIdAddress;
    /**
     * The user agent for the browser corresponding to the event.
     * Do not hash
     */
    @JsonProperty("client_user_agent")
    private String clientUserAgent;
    /**
     * A two-letter country code in lowercase. Example: us.
     * Hashing Needed
     */
    private String country;
    /**
     * A city in lower-case without spaces or punctuation. Example: menlopark.
     * Hashing Needed
     */
    private String ct;
    /**
     * A date of birth given as year, month, and day. Example: 19971226 for December 26, 1997.
     * Hashing Needed
     */
    private String db;
    /**
     * An email address, in lowercase. Example: joe@eg.com
     * Hashing Needed
     */
    private String em;

    /**
     * Any unique ID from the advertiser, such as loyalty membership IDs, user IDs, and external cookie IDs. You can send one or more external IDs for a given event.
     * Hashing is recommended
     */
    @JsonProperty("external_id")
    private String externalId;

    /**
     * ID issued by Facebook when a person first logs into an instance of an app. This is also known as App-Scoped ID.
     * Do not hash
     */
    @JsonProperty("fb_login_id")
    private Integer fbLoginId;

    /**
     * The Facebook click ID value stored in the _fbc browser cookie under your domain.
     * Do not hash
     */
    private String fbc;
    /**
     * The Facebook browser ID value stored in the _fbp browser cookie under your domain
     * Do not hash
     */
    private String fbp;

    /**
     * A first name in lowercase. Example: joe.
     * Hashing Needed
     */
    private String fn;
    /**
     * Gender, in lowercase. Either f or m.
     * Hashing Needed
     */
    private String ge;
    /**
     * ID associated with a lead generated by Facebook's Lead Ads.
     * Do not hash
     */
    @JsonProperty("lead_id")
    private Integer leadId;
    /**
     * A last name in lowercase. Example: smith.
     * Hashing Needed
     */
    private String ln;
    /**
     * A phone number. Include only digits with country code, area code, and number. Example: 16505551212
     * Hashing Needed
     */
    private String ph;
    /**
     * A two-letter state code in lowercase. Example: ca.
     * Hashing Needed
     */
    private String st;
    /**
     * The subscription ID for the user in this transaction. This is similar to the order ID for an individual product. Example: anid1234.
     * Do not hash
     */
    @JsonProperty("subscription_id")
    private String subscriptionId;
    /**
     * If you are in the United States, this is a five-digit zip code. For other locations, follow each country's standards. Example: 94035 (for United States)
     * Hashing Needed
     */
    private String zp;
}
